#!/bin/bash
# script to run vasp
# make this file executable and put it into the system defaulted binary folder
# usage: vasp 

# get the path to the job directory containing the input file
dir_path=$(dirname $1)

# move into the job directory
cd $dir_path

# run lammps on the input file
# usage: path/to/vasp_binary
# Recommend to put lammps_binary in the system defaulted binary folder
vasp

#example for mpi run
#mpirun -np 2 vasp
#Code will change the number of processors based on input.yaml
